name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Update README with blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://rss.csdn.net/weixin_43308380/rss/map"
          readme_path: "README.md"
          max_post_count: "5"
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated README with latest blog posts"
          git push
